version: "3.8"

services:
  frontend:
    build:
      context: ../front-end
      dockerfile: Dockerfile
    volumes:
      - ../front-end:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/eventplaningdb
    env_file:
      - .env.docker
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventplaningdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf:ro 
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
